import './globals.css';

import type { Metadata } from 'next';
import { Anonymous_Pro, Plus_Jakarta_Sans, Roboto } from 'next/font/google';

import { cn } from '@/lib/utils';

import GlobalTabs from './components/GlobalTabs';

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta',
  subsets: ['latin'],
});

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

const anonymousPro = Anonymous_Pro({
  variable: '--font-anonymous-pro',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${plusJakartaSans.variable} ${roboto.variable} ${anonymousPro.variable} font-sans antialiased`,
          'mx-auto max-w-[1400px]',
        )}
      >
        <GlobalTabs />
        {children}
      </body>
    </html>
  );
}
